# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (every day at 03:00 am)
  schedule: [{cron: "0 3 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}

env:
  DESIRED_COMMIT_MESSAGE: Update github-metrics.svg - [Skip GitHub Action]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update metrics
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: kolayne
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_timezone: Europe/Moscow
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_languages: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_colors: github
          plugin_languages_indepth: yes
          plugin_languages_limit: 32
          plugin_languages_recent_days: 32
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          repositories: 1000
          repositories_affiliations: owner collaborator organization_member

      - name: Checkout
        uses: actions/checkout@v3
        with:
          # It is required to fetch all commits to be able to force-push later
          fetch-depth: 0

      - name: Prepare commits to combine, if needed
        # If either this or the previous commit is meaningful, should do nothing.
        # Otherwise, combine the two.
        id: commits_preparer
        run: |
          set -e
          echo "::set-output name=should_commit::false"  # False by default

          # Look at the last two commits to see if they are what we need
          for i in 1 2; do
            if [[ "$(git log -1 --pretty=%B)" != "$DESIRED_COMMIT_MESSAGE" ]]; then
              exit 0  # A meaningful message. Thus, nothing to do further
            fi
            git reset --soft HEAD^
          done

          echo "::set-output name=should_commit::true"

      - name: Combine commits
        if: steps.commits_preparer.outputs.should_commit == true
        uses: EndBug/add-and-commit@v9
        with:
          message: ${{env.DESIRED_COMMIT_MESSAGE}}

          default_author: github_actions

          pathspec_error_handling: exitImmediately

          push: origin master --force
